### PR TITLE
bosh backup

### PR DESCRIPTION
**Pull request by voelzmo**
first version of what the restore process could look like. backup of the director still tbd.

### CODE REVIEW

**Comment by voelzmo** [comment]
@cppforlife Any comments/ideas/suggestions about this?

**Comment by cppforlife** [comment]
we are planning to introduce errands that run on existing instances (one or many). i think it could resolve some of the questions at the end of the doc.

**Comment by cppforlife** [comment]
is this something that is covered by bbr or do we want to proceed with further snapshotting functionality?

**Comment by voelzmo** [comment]
I guess using bbr and some reasonable service scripts covers this.

On 24. Nov 2017, at 16:56, Dmitriy Kalinin <notifications@github.com<mailto:notifications@github.com>> wrote:


is this something that is covered by bbr or do we want to proceed with further snapshotting functionality?

**Pull request closed without merging**
