### PR TITLE
Create TOSCA Compliance within Cloud Foundry

### PR DESCRIPTION
**Pull request by deepak-vij**
My new proposal for TOSCA Compliance.

### CODE REVIEW

**Comment by rkoster** [comment]
I'm not sure but it looks like the other proposals are in the Markdown format. Converting this PR to markdown would increase the readability.

**Comment by rkoster** [comment]
Maybe you could add some links to additional information on TOSCA, for people who are new to it and would like to know more (like myself :smile:).

**Comment by deepak-vij** [comment]
Hi Ruben, following are the few links for TOSCA. Thanks.

http://docs.oasis-open.org/tosca/TOSCA/v1.0/os/TOSCA-v1.0-os.html
http://www.slideshare.net/YaronParasol/tosca-explained

**Comment by cppforlife** [comment]
Hey @deepak-vij, thanks for getting this PR going. 

Before pulling in this PR, could you add a bit more details to it to clarify how you see BOSH concepts (stemcells, releases, CPIs, deployments) being described with TOSCA with some markup examples.

**Comment by rkoster** [comment]
@deepak-vij thanks for the links

**Comment by deepak-vij** [comment]
Hi Dmitriy, following is a bit more background on how BOSH constructs such as **“Stemcell”**, **“Release”**, **“Deployment”**, & **“CPI”** may map into corresponding TOSCA concepts. This is very high level preliminary analysis in order to provide you a brief overview of what all it entails as far as TOSCA mapping with BOSH orchestration environment. As a follow work, we may have to do in-depth analysis for exactly determining the level-of-effort for this effort.

The way the whole process works is by defining the cloud application orchestration plan – also called Blueprint. The main part of the plan is written in a declarative YAML DSL (Domain Specific Language). This DSL follows the concepts of OASIS TOSCA specifications. Blueprint consists of “Topologies”. A Topology is a graph of application components and their relationships described in YAML. One can think about it as application components being the vertices of the graph and the relationships being the edges of the graph. Each component is described by a YAML object denoted as a YAML list entry. Components can be of 3 levels:
* **Infrastructure** - Components provided by the IaaS layer (e.g. VM, virtual network, virtual load balancer or storage volume) or by non-cloud physical or virtualized layer (e.g. Host and storage volume)
*  **Platform/Middleware** - Components that serve as the application containers (such as web-servers, application servers, message servers and database servers)
* **Application modules** - The different application artifacts that needs to be deployed and configured on top of the middleware (such as application binaries, application configuration files, database schemas etc.)

# TOSCA Overview
Firstly, here is a high level overview of TOSCA (Topology and Orchestration Specification for Cloud Applications). TOSCA is an open standard from OASIS that aims to enhance portability and management of cloud applications and services. In practical terms, a TOSCA service template (or application blueprint) is a document written in YAML that adheres to the syntax defined by the TOSCA specification. The template is submitted to a TOSCA-compliant orchestration engine (for example Cloudify TOSCA Orchestration Engine from GigaSpaces) and, as a result, the application gets deployed and configured on the cloud provider of choice.
untitled2
TOSCA uses the following concepts for the Topology parts:
* Components are called **nodes**
* Components relationships are called **relationships**

Topologies are defined using the **blueprint** YAML file. Below is a sample TOSCA blueprint from VMWare TOSCA-vCloud-plugin that contains a virtual machine that is connected to a network and has a public IP address. The blueprint also defines that a web server (ngnix) should be installed on the virtual machine and that ports 22 and 80 should be accessible from outside.

This simple blueprint illustrates two important concepts in TOSCA orchestration:
* **Infrastructure Provisioning**: a VM is instantiated on a virtual datacenter from a template and network resources are configured according to the template
* **Software configuration**: in this case, a web server gets installed and started on the VM created previously

Baseline blueprint information is customized/configured using the input values passed inside an input YAML file (see below).

TOSCA workflows orchestrate the different management operations offered by the nodes to fulfill their task. For example, Cloudify TOSCA implementation comes with two built-in workflows called “install” and “uninstall”.

# BOSH & TOSCA Mapping
* **Release**: This information will be defined using blueprint YAML definitions by leveraging various **nodes** and **relationships** as prescribed by TOSCA.
* **Deployment**: Deployment in BOSH consists of all the actual parameter values (deployment knobs) at the time of actual deployment. As described earlier that baseline TOSCA blueprint information is customized/configured using the input values passed inside an input YAML file.
* **Stemcell**: As we all know that a stemcell is a VM template containing an OS image such as standard Ubuntu distribution etc. Additionally, a BOSH agent is also embedded in the template so that BOSH can take control of VMs cloned from the stemcell. TOSCA topology constructs such as **nodes** and **relationships** can used to define the whole stemcell definition process.
* **CPI**: BOSH Cloud-Provider-Interface is essentially IaaS specific interface for deploying CloudFoundry application environment within the native IaaS infrastructure. In the TOSCA, each IaaS specific CPI would be implemented as a plugin module (such as CF-OpenStack-plugin, CF-AWS-plugin, CF-Baremetal-plugin etc.).

# vCloud-blueprint.yaml
node_templates:

    example_server:
        type: cloudify.vcloud.nodes.Server
        properties:
            server:
                name: { get_input: server_name }
                catalog: { get_input: catalog }
                template: { get_input: template }
                hardware:
                    cpu: 3
                    memory: 2048
                guest_customization:
                    computer_name: { get_input: server_name }
                    public_keys:
                        - { get_property: [ssh_keypair, public_key] }
            install_agent: false
            management_network: { get_input: network_name }
            vcloud_config: { get_property: [vcloud_configuration, vcloud_config] }
        relationships:
            - target: example_port
              type: cloudify.vcloud.server_connected_to_port
            - target: example_public_ip
              type: cloudify.vcloud.server_connected_to_public_nat

    example_port:
        type: cloudify.vcloud.nodes.Port
        properties:
            port:
                network: { get_input: network_name }
                ip_allocation_mode: pool
                primary_interface: true

    example_public_ip:
        type: cloudify.vcloud.nodes.PublicNAT
        properties:
            nat:
                edge_gateway: { get_input: gateway_name }
                public_ip: { get_input: public_ip }
            rules:
                - type: SNAT
                - type: DNAT
                  protocol: tcp
                  original_port: 22
                  translated_port: 22
                - type: DNAT
                  protocol: tcp
                  original_port: 80
                  translated_port: 80

    nginx_service:
        type: cloudify.nodes.ApplicationServer
        interfaces:
            cloudify.interfaces.lifecycle:
                start:
                    implementation: fabric.fabric_plugin.tasks.run_commands
                    inputs:
                      commands:
                        - sudo apt-get update
                        - sudo apt-get install -y nginx
                        - sudo service nginx start
                      fabric_env:
                        host_string: { get_input: public_ip }
                        host: { get_input: public_ip }
                        user: { get_property: [ssh_keypair, public_key, user] }
                        key_filename: { get_property: [ssh_keypair, private_key_path] }
                        disable_known_hosts: True
        relationships:
          - type: cloudify.relationships.contained_in
            target: example_server

# input.yaml
vcloud_username: email@company.com
vcloud_password: 'mysecretpassord'
vcloud_instance: d7a623de-1183-46a9-9b02-9043ca68f881
vcloud_vdc: VDC1

vcloud_url: iam.vchs.vmware.com
vcloud_api_version: '5.7'
vcloud_service_type: ondemand

catalog: 'Public Catalog'
template: 'Ubuntu Server 12.04 LTS (amd64 20150127)'
network_name: default-routed-network
gateway_name: gateway
server_name: hellow
public_ip: 107.189.85.67
ssh_user: ubuntu
ssh_private_key_path: ~/.ssh/id_rsa_manager
ssh_public_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFlYX8JkGVKtCUmSi4NStzT+qCqRuFaqP6gzxly7atmfGTXGymOwf56mP9j1vM4a5OLSwTS/xQb9RrHPWZmohqApvaIyM9MQTF1EkoPtb39/tLDyWiAS/czXMGx2VWCqRAfZhdoUn1pd14hyfCUDqDv0Guo3Z/VF5dqHVSB0dHgjNeAYCsWXQhtm+GBxBUxohGaPNzO6wQZvhOnJT2KaVDDlZa3SsK1s+Lx0YDW3s2AkB759dRi71m/kFQBBcXSo2lqg6hRDCgbO6xtVcw/fi3IGsOVTXeZW2dwDq3B10AZZcrsQJAGrIXtVDw2LPnf0hISQkVV43ZNE4Aa5OEPQ5T manager'

**Comment by cppforlife** [comment]
going to close this one for now. dont see a lot of interest from other on this topic.

**Pull request closed without merging**
